// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 필드 타입.
 */
export type FieldType = "integer" | "number" | "boolean" | "string" | "select" | "multi_select" | "symbol" | "symbols" | "multi_timeframe";
