// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fragment 참조.
 */
export type FragmentRef = { 
/**
 * Fragment ID
 */
id: string, 
/**
 * 필수 여부
 */
required: boolean, };
