// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldSchema } from "./FieldSchema";
import type { FragmentCategory } from "./FragmentCategory";

/**
 * 재사용 가능한 UI 스키마 조각 (Fragment).
 *
 * Fragment는 여러 전략에서 공통으로 사용되는 설정 그룹입니다.
 * 예: RSI 설정, 트레일링 스탑 설정 등
 */
export type SchemaFragment = { 
/**
 * Fragment ID (예: "indicator.rsi", "risk.trailing_stop")
 */
id: string, 
/**
 * Fragment 이름 (한글)
 */
name: string, 
/**
 * 설명
 */
description: string | null, 
/**
 * 카테고리
 */
category: FragmentCategory, 
/**
 * 필드 목록
 */
fields: Array<FieldSchema>, 
/**
 * 다른 Fragment에 대한 의존성
 */
dependencies: Array<string>, };
